/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pckGui;

import javax.swing.JOptionPane;
import pckDao.classUsuario;
import pckEntidad.Usuario;

/**
 *
 * @author Katherine
 */
public class frmInicioSesion extends javax.swing.JFrame {
    int i=0;
    classUsuario oUserDao=new classUsuario();
    void mensaje(String men){
        JOptionPane.showMessageDialog(this, men,"Alerta",1);
    }
    void limpiar(){
        txtContraseña.setText("");
        txtusuario.setText("");
        txtusuario.setFocusable(true);
    }
   
    /**
     * Creates new form frmInicioSesion
     */
    public frmInicioSesion() {
        initComponents();
        i=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresar = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONTROL DE ACCESO");

        btnIngresar.setText("INGRESAR");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Contraseña:");

        jLabel1.setText("Usuario:");

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(txtContraseña)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNuevo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        i++;
        if(i==3){
            mensaje("Intentos 3 de 3 permitidos");
            System.exit(0);
        }
//1.Caso A: Si hay campos vacios (STOP)
        if(txtusuario.getText().isEmpty() || txtusuario.getText().isEmpty()){
            mensaje("Complete Campos Vacios");
            limpiar();
        }
//1.Caso B: Si no hay campos vacios (NEXT)
        else {
            Usuario ousuario=oUserDao.buscarUser(txtusuario.getText().trim());          
//2. Caso A: Si el Usuario NO NO NO NO NO NO NO EXISTE (STOP)  
            if(ousuario==null){ 
                mensaje("NO EXISTE");limpiar(); limpiar();
            }
//2. Caso B: Si el Usuario SI EXISTE (NEXT)
            else {
//3. Caso A: Si el Usuario tiene el ESTADO == DESACTIVADO DESACTIVADO DESACTIVADO FALSE (STOP)
                if(ousuario.getEstado().equalsIgnoreCase("Desactivado")){
                    mensaje("Cuenta de Usuario Desactivado"); limpiar();
                }
//3. Caso B: Si el USUARIO tiene el ESTADO == ACTIVADO true (NEXT)                
                else if(ousuario.getEstado().equalsIgnoreCase("Activo")){
//4. Caso A: Si solo LA CONTRASEÑA ES CORRECTA (NEXT) 
                    if(ousuario.getContraseña().equalsIgnoreCase(txtContraseña.getText().trim())){
//5. Caso A: Si el usuario es SUPERVISOR ... ya ingreso  (NEXT)
                        int espacio=ousuario.getNombre().indexOf(" ");
                            String usuario=ousuario.getNombre().substring(0, espacio)+" "+ousuario.getApellido().substring(0);
                          if(ousuario.getNivel().equalsIgnoreCase("Supervisor")){
                            //frmMenu;
                                frmMenu vent=new frmMenu();
                                
                            vent.setVisible(true);vent.setLocationRelativeTo(null);vent.setResizable(false);
                            vent.jMenu6.setVisible(true);
                            
                            
                            vent.obtenercodLogin(ousuario.getCodUser());
                            vent.lblUsuario.setText(usuario);this.setVisible(false);
                        }
//5. Caso B: Si el usuario es EMPLEADO ... ya ingreso          (NEXT)              
                        else if(ousuario.getNivel().equalsIgnoreCase("Empleado")) {
                            //frmMenu  visible=false algunos comandos;
                            frmMenu vent=new frmMenu();
                            vent.setVisible(true);vent.setLocationRelativeTo(null);vent.setResizable(false);
                            vent.obtenercodLogin(ousuario.getCodUser());
                            vent.jMenu6.setVisible(false);
                            vent.lblUsuario.setText(usuario);this.setVisible(false);
                        }
//5. Caso C: Si el usuario tiene NULL NULL NULL NULL en el campo NIVEL NIVEL NIVEL (Revisar Campos)                        
                        else mensaje("No es Ni Empleado ni SuperVisor"); limpiar();
                    }
//4. Caso B: Si SOLO LA CONTRASEÑA ES INCORRECTA INCORRECTA INCORRECTA (Revisar texto)                   
                    else {mensaje("COntraseña Incorrecta");txtContraseña.setText(""); }
                 }
//3. Caso C: Si el USUARIO tiene el ESTADO == NULL NULL NULL                
                else mensaje("La Cuenta no esta Activado ni Desactivado"); limpiar();
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btnNuevoActionPerformed

            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
