/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pckGui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pckDao.classEventoDao;
import pckDao.classTipoPagoDao;
import pckEntidad.Evento;
import pckEntidad.TipoPago;

/**
 *
 * @author HOME
 */
public class frmListarOpcionPago extends javax.swing.JFrame {

    classTipoPagoDao oTipoPagoDao=new classTipoPagoDao();
    
   String idLogin="";
      void obtenerIdLogin(String cod){
      idLogin=cod;
    }
    void agregarEvento(String evento){
        
        classEventoDao oEventoDao=new classEventoDao();
     //  lblUsuario.setText("aRios");
        Evento unEvento=new Evento(1,idLogin, evento, "Opcion Pago", frmMenu.lblFecha.getText()+" "+frmMenu.lblHora.getText()+" "+frmMenu.lblAmPm.getText(), ""+frmMenu.lblFecha.getText(), "No");
        mensaje(oEventoDao.agregarEvento(unEvento));
    }
    
    void listarOpcionPago(){
        DefaultTableModel mod=new DefaultTableModel();
        String []columnas={"Codigo","Nombre Opcion Pago"};
        mod.setColumnIdentifiers(columnas);
        
        ArrayList<TipoPago> lista=oTipoPagoDao.listarTipoPago();
        for (TipoPago otipoPago : lista) {
            Object data[]={otipoPago.getIdOpcionPago(),otipoPago.getNombreOpcionPago()};
        mod.addRow(data);
        }  tblListaOpcionPago.setModel(mod); lblFilas.setText(""+tblListaOpcionPago.getRowCount());
    }
    
    void desBLoqBtn(boolean  valor){
        btnActualizar.setEnabled(valor);
        btnEliminar.setEnabled(valor);
    }
    
    void mensaje(String men){
        JOptionPane.showMessageDialog(this, men,"Aviso",1);
    }
    void limpiar(){
        txtidOpcionPago.setText("");
        txtnombreOpcionPago.setText("");
    }
    
    /**
     * Creates new form frmListarOpcionPago
     */
    public frmListarOpcionPago() {
        initComponents();
        listarOpcionPago();
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaOpcionPago = new javax.swing.JTable();
        pnlControles = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnIraMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtidOpcionPago = new javax.swing.JTextField();
        txtnombreOpcionPago = new javax.swing.JTextField();
        lblFilas = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenimiento Opcion Pago");

        tblListaOpcionPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblListaOpcionPago);

        pnlControles.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Controles:"));

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnIraMenu.setText("Ir a Menú");
        btnIraMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIraMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlesLayout = new javax.swing.GroupLayout(pnlControles);
        pnlControles.setLayout(pnlControlesLayout);
        pnlControlesLayout.setHorizontalGroup(
            pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlControlesLayout.createSequentialGroup()
                        .addGroup(pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIraMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlControlesLayout.setVerticalGroup(
            pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnIraMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Código:");

        jLabel2.setText("Opcion de Pago:");

        lblFilas.setText("Total de Filas: xx");

        lblUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario:"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidOpcionPago, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombreOpcionPago, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFilas)
                                .addGap(533, 533, 533))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(pnlControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtidOpcionPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnombreOpcionPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFilas))
                    .addComponent(pnlControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        if(btnNuevo.getText().equalsIgnoreCase("NUEVO")){
            limpiar();
            txtnombreOpcionPago.setEditable(false);desBLoqBtn(false);
        }else if(btnNuevo.getText().equalsIgnoreCase("CANCELAR")){
            txtnombreOpcionPago.setEditable(false);desBLoqBtn(false);
            btnNuevo.setText("NUEVO");
            limpiar();
            btnBuscar.setText("BUSCAR");btnAgregar.setText("AGREGAR");btnActualizar.setText("AGREGAR");
        }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(btnAgregar.getText().equalsIgnoreCase("AGREGAR")){
            limpiar();
            txtidOpcionPago.setText(""+(oTipoPagoDao.codigoTipoPago()+1));
            txtnombreOpcionPago.setEditable(true);
            txtnombreOpcionPago.requestFocus();
            btnAgregar.setText("ACEPTAR");btnNuevo.setText("CANCELAR");
        }
        else if(btnAgregar.getText().equalsIgnoreCase("ACEPTAR")){
            if(txtidOpcionPago.getText().isEmpty() || txtnombreOpcionPago.getText().isEmpty()){
            mensaje("No dejar Campos Vacios");
        }else {
            mensaje(oTipoPagoDao.agregarTipoPago(new TipoPago(Integer.parseInt(txtidOpcionPago.getText()), txtnombreOpcionPago.getText(),"No")));
            agregarEvento("Insertar");
            listarOpcionPago();
            limpiar();
        }btnAgregar.setText("AGREGAR");btnNuevo.setText("NUEVO");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(btnBuscar.getText().equalsIgnoreCase("BUSCAR")){
            limpiar(); txtidOpcionPago.setEditable(true);txtidOpcionPago.requestFocus();
            btnBuscar.setText("ACEPTAR");
            btnNuevo.setText("CANCELAR");
        }
        else if(btnBuscar.getText().equalsIgnoreCase("ACEPTAR")){
              if(txtidOpcionPago.getText().isEmpty()){
            mensaje("Ingresar Codigo");txtidOpcionPago.requestFocus();
        }else {
            TipoPago oTipoPago=oTipoPagoDao.buscarTipoPago(Integer.parseInt(txtidOpcionPago.getText()));
            if(oTipoPago==null){
            mensaje("Codigo no Existe");limpiar();txtidOpcionPago.requestFocus();
            }else {
                txtnombreOpcionPago.setText(oTipoPago.getNombreOpcionPago());
                txtnombreOpcionPago.setEditable(false); 
                desBLoqBtn(true);
            }
        }btnBuscar.setText("BUSCAR");btnNuevo.setText("NUEVO");
            txtnombreOpcionPago.setEditable(false); txtidOpcionPago.setEditable(false);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
         if(btnActualizar.getText().equalsIgnoreCase("ACTUALIZAR")){
           txtnombreOpcionPago.setEditable(true);
           txtnombreOpcionPago.requestFocus();
           
           btnActualizar.setText("ACEPTAR");btnNuevo.setText("CANCELAR");
       }else if(btnActualizar.getText().equalsIgnoreCase("ACEPTAR")){
            if(txtidOpcionPago.getText().isEmpty() || txtnombreOpcionPago.getText().isEmpty()){
            mensaje("No dejar Campos Vacios");txtnombreOpcionPago.requestFocus();
        }else {
                mensaje(oTipoPagoDao.actualizarTipoPago(new TipoPago(Integer.parseInt(txtidOpcionPago.getText()),txtnombreOpcionPago.getText(), "No")));
               agregarEvento("Modificar");
                listarOpcionPago();
                desBLoqBtn(false);
            limpiar();
        }
            btnActualizar.setText("ACTUALIZAR");btnNuevo.setText("NUEVO");
       }
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(txtidOpcionPago.getText().isEmpty()){
            mensaje("Ingresar Codigo");limpiar();
            txtidOpcionPago.setEditable(true);
            txtidOpcionPago.requestFocus();
            }else {
            int x=Integer.parseInt(""+JOptionPane.showConfirmDialog(this, "Seguro de Eliminar la Opcion Pago "+txtnombreOpcionPago.getText()+" ????"));
            if(x==0){
                mensaje(oTipoPagoDao.eliminadoLogicoTipoPago(Integer.parseInt(txtidOpcionPago.getText())));
               agregarEvento("Eliminar");
                listarOpcionPago();
            
            }limpiar();desBLoqBtn(false);txtnombreOpcionPago.setEditable(false);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnIraMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIraMenuActionPerformed
        // TODO add your handling code here:
//        frmMenu vent=new frmMenu();
//        vent.setLocationRelativeTo(null);
//        vent.setResizable(false);vent.setVisible(true);vent.lblUsuario.setText(lblUsuario.getText());
        this.dispose();
    }//GEN-LAST:event_btnIraMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListarOpcionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListarOpcionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListarOpcionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListarOpcionPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListarOpcionPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIraMenu;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFilas;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlControles;
    private javax.swing.JTable tblListaOpcionPago;
    private javax.swing.JTextField txtidOpcionPago;
    private javax.swing.JTextField txtnombreOpcionPago;
    // End of variables declaration//GEN-END:variables
}
