/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pckGui;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pckDao.classCategoriaDao;
import pckDao.classEventoDao;
import pckEntidad.Categoria;
import pckEntidad.Evento;

/**
 *
 * @author HOME
 */
public class frmListarCategoria extends javax.swing.JFrame {

    classCategoriaDao ocategoriaDao=new classCategoriaDao();
    
    String idLogin="";
      void obtenerIdLogin(String cod){
      idLogin=cod;
    }
    void agregarEvento(String evento){
        
        classEventoDao oEventoDao=new classEventoDao();
     //  lblUsuario.setText("aRios");
        Evento unEvento=new Evento(1,idLogin, evento, "Categoria", frmMenu.lblFecha.getText()+" "+frmMenu.lblHora.getText()+" "+frmMenu.lblAmPm.getText(), ""+frmMenu.lblFecha.getText(), "No");
        mensaje(oEventoDao.agregarEvento(unEvento));
    }
    
    void limpiar(){
        txtAbreviatura.setText("");
        txtCodCategoria.setText("");
        txtNombreCategoria.setText("");
        
    }
    void mensaje(String men){
        JOptionPane.showMessageDialog(this, men,"Aviso",1);
    }
    void listarCategoria(){
        DefaultTableModel mod=new DefaultTableModel();
        String columnas[]={
          "Código","Nombre Categoria","Abreviatura"  
        };mod.setColumnIdentifiers(columnas);
        ArrayList<Categoria> lista=ocategoriaDao.listarCategoria();
        for (Categoria categoria : lista) {
            Object data[]={
              categoria.getIdCategoria(),categoria.getNombreCategoria(),categoria.getAbreviatura()
            };mod.addRow(data);
        }tblLista.setModel(mod);lblFilasCategoria.setText("Filas Encontradas: "+tblLista.getRowCount());
    }
    
      void soloNumeros(KeyEvent evt,String cad){
        int longitud=0;
        char x=evt.getKeyChar();
        
        longitud=cad.length();
        
        if(Character.isLetter(x)){
            getToolkit().beep();
            evt.consume();
       //     JOptionPane.showMessageDialog(this, "INGRESAR SOLO NUMEROS....");
        }
        
        if(longitud>=50){
            evt.consume();
        }
    }
    
      void soloNumerosCAnt(KeyEvent evt,String cad){
    //    int longitud=0;
        char x=evt.getKeyChar();
        
      //  longitud=cad.length();
        
        if(Character.isLetter(x)){
            getToolkit().beep();
            evt.consume();
       //     JOptionPane.showMessageDialog(this, "INGRESAR SOLO NUMEROS....");
        }
        
      
    }
    void soloTexto(KeyEvent evt,String cad){
         char x=evt.getKeyChar();
         
         if(Character.isDigit(x)){
             getToolkit().beep();
             evt.consume();
             JOptionPane.showMessageDialog(this, "INGRESAR SOLO TEXTO....");
         }
    }
    
    void desBLoqTxt(boolean  valor){
        txtAbreviatura.setEditable(valor);
        txtNombreCategoria.setEditable(valor);
    }
    void desBLqBtn(boolean valor){
        btnActualizar.setEnabled(valor);
        btnEliminar.setEnabled(valor);
    }
    /**
     * Creates new form frmListarCategoria
     */
    public frmListarCategoria() {
        initComponents();
        listarCategoria();
        desBLoqTxt(false);txtCodCategoria.setEditable(false);
        desBLqBtn(false);
        limpiar();
// txtCodCategoria.setText(""+(ocategoriaDao.codCategoria()+1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCodCategoria = new javax.swing.JTextField();
        txtNombreCategoria = new javax.swing.JTextField();
        txtAbreviatura = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnIrMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        lblFilasCategoria = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos de la Categoria:"));

        txtNombreCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreCategoriaKeyTyped(evt);
            }
        });

        jLabel1.setText("Codigo:");

        jLabel3.setText("Abreviatura:");

        jLabel2.setText("Nombre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAbreviatura, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAbreviatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Controles:"));

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnIrMenu.setText("Ir a Menú");
        btnIrMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIrMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnIrMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLista);

        lblFilasCategoria.setText("Filas Encontradas: xx");

        lblUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario:"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFilasCategoria)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFilasCategoria)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        if(btnNuevo.getText().equalsIgnoreCase("NUEVO")){
            limpiar();
            desBLoqTxt(false);desBLqBtn(false);
        }else if(btnNuevo.getText().equalsIgnoreCase("CANCELAR")){
            desBLoqTxt(false);desBLqBtn(false);
            btnNuevo.setText("NUEVO");
            limpiar();
            btnBuscar.setText("BUSCAR");btnAgregar.setText("AGREGAR");btnActualizar.setText("ACTUALIZAR");
        }
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(btnAgregar.getText().equalsIgnoreCase("AGREGAR")){
            limpiar();
            txtCodCategoria.setText(""+(ocategoriaDao.codCategoria()+1));
            desBLoqTxt(true);
            txtNombreCategoria.requestFocus();
            btnAgregar.setText("ACEPTAR");btnNuevo.setText("CANCELAR");
        }
        else if(btnAgregar.getText().equalsIgnoreCase("ACEPTAR")){
            if(txtCodCategoria.getText().isEmpty() || txtNombreCategoria.getText().isEmpty()){
            mensaje("No dejar Campos Vacios");
        }else {
            mensaje(ocategoriaDao.agregarCategoria(new Categoria(Integer.parseInt(txtCodCategoria.getText()), txtNombreCategoria.getText(), txtAbreviatura.getText(),"No")));
                agregarEvento("Insertar");
            listarCategoria();
            limpiar();
        }btnAgregar.setText("AGREGAR");btnNuevo.setText("NUEVO");
        }
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(btnBuscar.getText().equalsIgnoreCase("BUSCAR")){
            limpiar(); txtCodCategoria.setEditable(true);txtCodCategoria.requestFocus();
            btnBuscar.setText("ACEPTAR");
            btnNuevo.setText("CANCELAR");
        }
        else if(btnBuscar.getText().equalsIgnoreCase("ACEPTAR")){
              if(txtCodCategoria.getText().isEmpty()){
            mensaje("Ingresar Codigo");txtCodCategoria.requestFocus();
        }else {
            Categoria ocategoria=ocategoriaDao.buscarCategoria(Integer.parseInt(txtCodCategoria.getText()));
            if(ocategoria==null){
                mensaje("Codigo no Existe");limpiar();txtCodCategoria.requestFocus();
            }else {
                txtNombreCategoria.setText(ocategoria.getNombreCategoria());
                txtAbreviatura.setText(ocategoria.getAbreviatura());
                desBLoqTxt(false); 
                desBLqBtn(true);
            }
        }btnBuscar.setText("BUSCAR");btnNuevo.setText("NUEVO");
            desBLoqTxt(false); txtCodCategoria.setEditable(false);
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
       if(btnActualizar.getText().equalsIgnoreCase("ACTUALIZAR")){
           desBLoqTxt(true);
           txtNombreCategoria.requestFocus();
           
           btnActualizar.setText("ACEPTAR");btnNuevo.setText("CANCELAR");
       }else if(btnActualizar.getText().equalsIgnoreCase("ACEPTAR")){
            if(txtCodCategoria.getText().isEmpty() || txtNombreCategoria.getText().isEmpty()){
            mensaje("No dejar Campos Vacios");txtNombreCategoria.requestFocus();
        }else {
            mensaje(ocategoriaDao.actualizarCategoria(new Categoria(Integer.parseInt(txtCodCategoria.getText()),txtNombreCategoria.getText(),txtAbreviatura.getText(),"No")));
                agregarEvento("Modificar");
            listarCategoria();
            desBLqBtn(false);
            limpiar();
        }
            btnActualizar.setText("ACTUALIZAR");btnNuevo.setText("NUEVO");
       }
        
        
       
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(txtCodCategoria.getText().isEmpty()){
            mensaje("Ingresar Codigo");limpiar();
            txtCodCategoria.setEditable(true);
            txtCodCategoria.requestFocus();
            }else {
            int x=Integer.parseInt(""+JOptionPane.showConfirmDialog(this, "Seguro de Eliminar la CATEGORIA "+txtNombreCategoria.getText()+" ????"));
            if(x==0){
            mensaje(ocategoriaDao.eliminarCategoria(Integer.parseInt(txtCodCategoria.getText())));
                agregarEvento("Eliminar");
            listarCategoria();
            
            }limpiar();desBLqBtn(false);desBLoqTxt(false);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnIrMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrMenuActionPerformed
        // TODO add your handling code here:
//        frmMenu vent=new frmMenu();
//        vent.setLocationRelativeTo(null);
//        vent.setResizable(false); vent.setVisible(true);
//        vent.lblUsuario.setText(lblUsuario.getText());
        this.dispose();
    }//GEN-LAST:event_btnIrMenuActionPerformed

    private void txtNombreCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCategoriaKeyTyped
        // TODO add your handling code here:
        soloTexto(evt, txtNombreCategoria.getText());
    }//GEN-LAST:event_txtNombreCategoriaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListarCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIrMenu;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFilasCategoria;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblLista;
    private javax.swing.JTextField txtAbreviatura;
    private javax.swing.JTextField txtCodCategoria;
    private javax.swing.JTextField txtNombreCategoria;
    // End of variables declaration//GEN-END:variables
}
