/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pckGui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pckDao.classEventoDao;
import pckDao.classUnidadMedida;
import pckEntidad.Evento;
import pckEntidad.UnidadMedida;

/**
 *
 * @author HOME
 */
public class frmListarUnidadMedida extends javax.swing.JFrame {
        classUnidadMedida oUnidMedidDao=new classUnidadMedida();
          
        void ingresarCod(){
            txtCodigoUnidMedida.setText(""+(oUnidMedidDao.cantUnidMed()+1));
        }
        
     String idLogin="";
      void obtenerIdLogin(String cod){
      idLogin=cod;
    }
    void agregarEvento(String evento){
        
        classEventoDao oEventoDao=new classEventoDao();
     //  lblUsuario.setText("aRios");
        Evento unEvento=new Evento(1,idLogin, evento, "Unidad Medida", frmMenu.lblFecha.getText()+" "+frmMenu.lblHora.getText()+" "+frmMenu.lblAmPm.getText(), ""+frmMenu.lblFecha.getText(), "No");
        mensaje(oEventoDao.agregarEvento(unEvento));
    }
        
        void listarUnidadMedida(){
         
            DefaultTableModel mod=new DefaultTableModel();
            String columnas[]={
                "Codigo","Nombre"
            };mod.setColumnIdentifiers(columnas);
            ArrayList<UnidadMedida> lista=oUnidMedidDao.listarUnidadMedida();
            for (UnidadMedida unidadMedida : lista) {
                Object data[]={
                  unidadMedida.getIdUnidadMedidad(),unidadMedida.getNombreMedida()
                };mod.addRow(data);
            }tblListaUnidMedida.setModel(mod);lblFilasUnidadMed.setText("Filas Encontradas: "+mod.getRowCount());
        }
        void limpiar(){
            txtNombreUndMedida.setText("");
        }
        void desBloqBtn(boolean valor){
            btnactualizar.setEnabled(valor);
            btnEliminar.setEnabled(valor);
        }
      
        void mensaje(String men){
            JOptionPane.showMessageDialog(this, men,"Alerta",1);
        }
    /**
     * Creates new form frmListarUnidadMedida
     */
    public frmListarUnidadMedida() {
        initComponents();
        listarUnidadMedida();
        desBloqBtn(false);txtCodigoUnidMedida.setEditable(false);
        txtNombreUndMedida.setEditable(false);
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnIrMenu = new javax.swing.JButton();
        txtNombreUndMedida = new javax.swing.JTextField();
        txtCodigoUnidMedida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFilasUnidadMed = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListaUnidMedida = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Unidad de Medida");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "CONTROLES:"));

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnactualizar.setText("ACTUALIZAR");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnIrMenu.setText("Ir Menú");
        btnIrMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnactualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIrMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnNuevo)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnactualizar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnIrMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtCodigoUnidMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoUnidMedidaActionPerformed(evt);
            }
        });
        txtCodigoUnidMedida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoUnidMedidaKeyPressed(evt);
            }
        });

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nombre:");

        lblFilasUnidadMed.setText("Filas Encontradas: xx");

        lblUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario:"));

        tblListaUnidMedida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblListaUnidMedida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreUndMedida)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCodigoUnidMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 151, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFilasUnidadMed))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoUnidMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreUndMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFilasUnidadMed))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
       if(btnNuevo.getText().equalsIgnoreCase("NUEVO")){
           limpiar();
           desBloqBtn(false);txtNombreUndMedida.setEditable(false);
       }else if(btnNuevo.getText().equalsIgnoreCase("CANCELAR")){
           txtNombreUndMedida.setEditable(false);
           desBloqBtn(false);
           btnNuevo.setText("NUEVO");
           limpiar();
           btnNuevo.setText("BUSCAR");btnAgregar.setText("AGREGAR");btnactualizar.setText("ACTUALIZAR");
       }
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
       if(btnBuscar.getText().equalsIgnoreCase("BUSCAR")){
           limpiar();txtCodigoUnidMedida.setEditable(true);txtCodigoUnidMedida.requestFocus();
           btnBuscar.setText("ACEPTAR");btnNuevo.setText("CANCELAR");
       }
       else if(btnBuscar.getText().equalsIgnoreCase("ACEPTAR"))
                if (txtCodigoUnidMedida.getText().isEmpty()){
                mensaje("Ingrese Codigo a Buscar");txtCodigoUnidMedida.requestFocus();
                }
                else {
                UnidadMedida ounidadmedida=oUnidMedidDao.buscarUnidadMedida(Integer.parseInt(txtCodigoUnidMedida.getText()));
                 if(ounidadmedida==null){
                  mensaje("No existe el Codigo");limpiar(); txtCodigoUnidMedida.requestFocus();
            }
                 else {
                txtNombreUndMedida.setText(ounidadmedida.getNombreMedida());
                txtNombreUndMedida.setEditable(false);desBloqBtn(true);
            }btnBuscar.setText("BUSCAR");btnNuevo.setText("NUEVO");
            txtCodigoUnidMedida.setEditable(false);txtNombreUndMedida.setEditable(false);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
     if(btnAgregar.getText().equalsIgnoreCase("AGREGAR")){
            limpiar();
            txtCodigoUnidMedida.setText(""+(oUnidMedidDao.cantUnidMed()+1));
            txtNombreUndMedida.setEditable(true);
            txtNombreUndMedida.requestFocus();
            btnAgregar.setText("ACEPTAR");btnNuevo.setText("CANCELAR");
        }
        else if(btnAgregar.getText().equalsIgnoreCase("ACEPTAR")){
            if(txtCodigoUnidMedida.getText().isEmpty() || txtNombreUndMedida.getText().isEmpty()){
            mensaje("No dejar Campos Vacios");txtNombreUndMedida.requestFocus();
        }else {
            mensaje(oUnidMedidDao.agregarUnidadMedida(new UnidadMedida(Integer.parseInt(txtCodigoUnidMedida.getText()),txtNombreUndMedida.getText(),"No")));
            agregarEvento("Insertar");
            listarUnidadMedida();
            limpiar();txtCodigoUnidMedida.setText("");
        }btnAgregar.setText("AGREGAR");btnNuevo.setText("NUEVO");
        }
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
             if(btnactualizar.getText().equalsIgnoreCase("ACTUALIZAR")){
           txtNombreUndMedida.setEditable(true);
           txtNombreUndMedida.requestFocus();
           
           btnactualizar.setText("ACEPTAR");btnNuevo.setText("CANCELAR");
       }else if(btnactualizar.getText().equalsIgnoreCase("ACEPTAR")){
            if(txtCodigoUnidMedida.getText().isEmpty() || txtNombreUndMedida.getText().isEmpty()){
            mensaje("No dejar Campos Vacios");txtNombreUndMedida.requestFocus();
        }else {
            mensaje(oUnidMedidDao.actualizarUnidadMedida(new UnidadMedida(Integer.parseInt(txtCodigoUnidMedida.getText()), txtNombreUndMedida.getText(), "No")));
            agregarEvento("Modificar");
            listarUnidadMedida();
            desBloqBtn(false);
            limpiar();
        }
            btnactualizar.setText("ACTUALIZAR");btnNuevo.setText("NUEVO");
       }
        
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         if(txtCodigoUnidMedida.getText().isEmpty()){
            mensaje("Ingresar Codigo");limpiar();
            txtCodigoUnidMedida.setEditable(true);
            txtCodigoUnidMedida.requestFocus();
            }else {
            int x=Integer.parseInt(""+JOptionPane.showConfirmDialog(this, "Seguro de Eliminar la CATEGORIA "+txtNombreUndMedida.getText()+" ????"));
            if(x==0){
            mensaje(oUnidMedidDao.eliminarUnidadMedida(Integer.parseInt(txtCodigoUnidMedida.getText())));
            agregarEvento("Eliminar");
            listarUnidadMedida();
            
            }limpiar();desBloqBtn(false);txtNombreUndMedida.setEditable(false);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnIrMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrMenuActionPerformed
        // TODO add your handling code here:
//        frmMenu vent=new frmMenu();
//        vent.setLocationRelativeTo(null);
//        vent.setVisible(false);vent.setVisible(true);
//        vent.lblUsuario.setText(lblUsuario.getText());
        this.dispose();
    }//GEN-LAST:event_btnIrMenuActionPerformed

    private void txtCodigoUnidMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoUnidMedidaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCodigoUnidMedidaActionPerformed

    private void txtCodigoUnidMedidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoUnidMedidaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtCodigoUnidMedidaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListarUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListarUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListarUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListarUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListarUnidadMedida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIrMenu;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnactualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFilasUnidadMed;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblListaUnidMedida;
    private javax.swing.JTextField txtCodigoUnidMedida;
    private javax.swing.JTextField txtNombreUndMedida;
    // End of variables declaration//GEN-END:variables
}
