/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pckGui;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pckDao.classCategoriaDao;
import pckDao.classEventoDao;
import pckDao.classProductoDao;
import pckDao.classUnidadMedida;
import pckEntidad.Categoria;
import pckEntidad.Evento;
import pckEntidad.Producto;
import pckEntidad.ProductoConsulta;
import pckEntidad.UnidadMedida;

/**
 *
 * @author HOME
 */
public class frmMantenimientoProductos extends javax.swing.JFrame {

    classProductoDao oProductoDao=new classProductoDao();
    classCategoriaDao ocategoriaDao=new classCategoriaDao();
    classUnidadMedida oUnidadMedida=new classUnidadMedida();
  
    String ruta;
    
      
    void mensaje(String men){
        JOptionPane.showMessageDialog(this, men,"Alerta",1);
    }
    void limpiar(){
        txtCodProducto.setText("");
        txtNombreProducto.setText("");
        txtPrecioUnitario.setText("");
        
        txtRutaarchivo.setText("");
        
        cboNombreCategoria.setSelectedIndex(0);
        cboNombreUniMed.setSelectedIndex(0);
    }
    void desBlqTxt(boolean  valor){
        txtNombreProducto.setEditable(valor);
        txtPrecioUnitario.setEditable(valor);
        cboNombreCategoria.setEnabled(valor);
        cboNombreUniMed.setEnabled(valor);
    }
    void desBloqBtn(boolean valor){
        btnActualizar.setEnabled(valor);
        btnEliminar.setEnabled(valor);
    }
    //true es desbloqueado
    
   String idLogin="";
      void obtenerIdLogin(String cod){
      idLogin=cod;
    }
    void agregarEvento(String evento){
        
        classEventoDao oEventoDao=new classEventoDao();
     //  lblUsuario.setText("aRios");
        Evento unEvento=new Evento(1,idLogin, evento, "Producto", frmMenu.lblFecha.getText()+" "+frmMenu.lblHora.getText()+" "+frmMenu.lblAmPm.getText(), ""+frmMenu.lblFecha.getText(), "No");
        mensaje(oEventoDao.agregarEvento(unEvento));
    }
    void ListarProd(){
         DefaultTableModel mod=new DefaultTableModel();
        String columnas[]={
          "Codigo","Nombre","Unidad Medida","Precio Unitario","Categoria"  
        };mod.setColumnIdentifiers(columnas);
        ArrayList<ProductoConsulta> lista=oProductoDao.listarProductosDetallado();
        for (ProductoConsulta oproducto : lista) {
            Object data[]={
                oproducto.getIdProducto(),oproducto.getNombreProd(),oproducto.getNombreUnidadMedida(),oproducto.getPrecioUnitario(),oproducto.getNombreCategoria()
            };mod.addRow(data);
        }tblLista.setModel(mod);lblFilas.setText("Filas Encontradas: "+tblLista.getRowCount());
    }
    void listarCategoria(){
        ArrayList<Categoria> lista=ocategoriaDao.listarCategoria();
        for (Categoria ocategoria : lista) {
            cboNombreCategoria.addItem(ocategoria.getNombreCategoria());
        }
    }
    void listarUnidadMedida(){
        ArrayList<UnidadMedida> lista=oUnidadMedida.listarUnidadMedida();
        for (UnidadMedida ounidadMedida : lista) {
            cboNombreUniMed.addItem(ounidadMedida.getNombreMedida());
        }
    }
    
    
    void tamaño(){
        txtCodProducto.setText(""+(oProductoDao.tamaño()+1));
    }
    
    /**
     * Creates new form frmMantenimientoProductos
     */
    public frmMantenimientoProductos() {
        initComponents();
        
             listarCategoria();listarUnidadMedida();
        // listar Tabla
        ListarProd();
        desBloqBtn(false);desBlqTxt(false);txtCodProducto.setEditable(false);
        limpiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        lblFilas = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cboNombreCategoria = new javax.swing.JComboBox();
        txtPrecioUnitario = new javax.swing.JTextField();
        cboNombreUniMed = new javax.swing.JComboBox();
        txtNombreProducto = new javax.swing.JTextField();
        txtCodProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnIrMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        lblImagenProducto = new javax.swing.JLabel();
        txtRutaarchivo = new javax.swing.JTextField();
        btnBuscarArchivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario:"));

        lblFilas.setText("Filas Encontradas: xx");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del Producto:"));

        jLabel2.setText("Nombre del Producto:");

        jLabel1.setText("Codigo:");

        cboNombreCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Seleccionar--" }));

        cboNombreUniMed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Seleccionar--" }));

        jLabel3.setText("Unidad Medida:");

        jLabel4.setText("Precio Unitario:");

        jLabel5.setText("Categoria:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreProducto)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cboNombreCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, 132, Short.MAX_VALUE)
                                .addComponent(cboNombreUniMed, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 247, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboNombreUniMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Controles:"));

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnIrMenu.setText("Ir a Menú");
        btnIrMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIrMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnIrMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLista);

        lblImagenProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBuscarArchivo.setText("...");
        btnBuscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtRutaarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))
                                    .addComponent(lblImagenProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFilas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImagenProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtRutaarchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscarArchivo))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblFilas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(btnAgregar.getText().equalsIgnoreCase("AGREGAR")){
          //  mensaje("Ingreso a AGREGAR");
            limpiar();
            txtCodProducto.setText(""+(oProductoDao.tamaño()+1));
            desBlqTxt(true);
            txtNombreProducto.requestFocus();
            btnAgregar.setText("ACEPTAR");btnNuevo.setText("CANCELAR");
        }
        else if(btnAgregar.getText().equalsIgnoreCase("ACEPTAR")){
           // mensaje("INGRESO ACEPTAR EMPIEZA");
            if(txtCodProducto.getText().isEmpty() || txtNombreProducto.getText().isEmpty() || txtPrecioUnitario.getText().isEmpty()){
                mensaje("No dejar Campos Vacios");
            }else if(!ruta.equals("")){
               // mensaje("ENTRO A GUARDAR");
                mensaje(oProductoDao.agregarNuevoProducto(Integer.parseInt(txtCodProducto.getText()), txtNombreProducto.getText(),cboNombreUniMed.getSelectedIndex(),
                        Double.parseDouble(txtPrecioUnitario.getText()),cboNombreCategoria.getSelectedIndex(), "No", ruta));
                agregarEvento("Insertar");
                ListarProd();
              limpiar();
              lblImagenProducto.setIcon(null);
            }btnAgregar.setText("AGREGAR");btnNuevo.setText("NUEVO");
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        if(btnNuevo.getText().equalsIgnoreCase("NUEVO")){
            limpiar();
            desBlqTxt(false);desBloqBtn(false);
        }
        else if(btnNuevo.getText().equalsIgnoreCase("CANCELAR")){
            desBlqTxt(false);desBloqBtn(false);
            btnNuevo.setText("NUEVO");
            limpiar();
            btnBuscar.setText("BUSCAR");btnAgregar.setText("AGREGAR");
            btnActualizar.setText("ACTUALIZAR");btnEliminar.setText("ELIMINAR");
        }

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(btnBuscar.getText().equalsIgnoreCase("BUSCAR")){
            limpiar(); txtCodProducto.setEditable(true);txtCodProducto.requestFocus();
            btnBuscar.setText("ACEPTAR");
            btnNuevo.setText("CANCELAR");
        }
        else if(btnBuscar.getText().equalsIgnoreCase("ACEPTAR")){
        
            if(txtCodProducto.getText().isEmpty()){
                mensaje("Ingresar Codigo");txtCodProducto.requestFocus();
            }else {
                
                Producto oProducto=oProductoDao.buscarunProducto(Integer.parseInt( txtCodProducto.getText()));
                
                if(oProducto==null){
                    mensaje("Codigo no Existe");limpiar();txtCodProducto.requestFocus();
                }else {
                    txtNombreProducto.setText(oProducto.getNombreProducto());
                    txtPrecioUnitario.setText(""+oProducto.getPrecioUnitario());
                    cboNombreCategoria.setSelectedIndex(oProducto.getIdCategoria());
                    cboNombreUniMed.setSelectedIndex(oProducto.getIdUnidadMedidad());
                    Image preview=Toolkit.getDefaultToolkit().getImage(ruta);
                    txtRutaarchivo.setText("");
                    ImageIcon icon=new ImageIcon(oProducto.getImagenProd().getScaledInstance(lblImagenProducto.getWidth(), lblImagenProducto.getHeight(),Image.SCALE_DEFAULT));
                    lblImagenProducto.setIcon(icon);
                    desBlqTxt(false);
                    desBloqBtn(true);
                }
            }btnBuscar.setText("BUSCAR");btnNuevo.setText("NUEVO");
            desBlqTxt(false); txtCodProducto.setEditable(false);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:}

        if(btnActualizar.getText().equalsIgnoreCase("ACTUALIZAR")){
            desBlqTxt(true);
            txtNombreProducto.requestFocus();

            btnActualizar.setText("ACEPTAR");btnNuevo.setText("CANCELAR");
        }else if(btnActualizar.getText().equalsIgnoreCase("ACEPTAR")){
            if(txtNombreProducto.getText().isEmpty() || txtPrecioUnitario.getText().isEmpty()){
                mensaje("No dejar Campos Vacios");txtNombreProducto.requestFocus();
            }else 
                //if(!ruta.equals(""))
            {
                mensaje(oProductoDao.actualizarNuevoProducto(Integer.parseInt(txtCodProducto.getText()), txtNombreProducto.getText(),
                        cboNombreUniMed.getSelectedIndex(),Double.parseDouble(txtPrecioUnitario.getText()),
                        cboNombreCategoria.getSelectedIndex(), "No", ruta));
               agregarEvento("Modificar");
                ListarProd();
                desBloqBtn(false);
                limpiar();
            }
            btnActualizar.setText("ACTUALIZAR");btnNuevo.setText("NUEVO");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(txtCodProducto.getText().isEmpty()){
            mensaje("Ingresar Codigo");limpiar();
            txtCodProducto.setEditable(true);
            txtCodProducto.requestFocus();
        }else {
            int x=Integer.parseInt(""+JOptionPane.showConfirmDialog(this, "Seguro de Eliminar la CATEGORIA "+txtNombreProducto.getText()+" ????"));
            if(x==0){
                mensaje(ocategoriaDao.eliminarCategoria(Integer.parseInt(txtCodProducto.getText())));
              agregarEvento("Eliminar");
                listarCategoria();

            }limpiar();desBloqBtn(false);desBlqTxt(false);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnIrMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrMenuActionPerformed

        this.dispose();

    }//GEN-LAST:event_btnIrMenuActionPerformed

    private void btnBuscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarArchivoActionPerformed
        // TODO add your handling code here:

        JFileChooser elegirImagen=new JFileChooser();
        elegirImagen.setMultiSelectionEnabled(false);
        int o=elegirImagen.showOpenDialog(this);
        
        if(o== JFileChooser.APPROVE_OPTION){
            ruta=elegirImagen.getSelectedFile().getAbsolutePath();
            
            txtRutaarchivo.setText(ruta);
            Image preview =Toolkit.getDefaultToolkit().getImage(ruta);
            if(preview !=null){
                lblImagenProducto.setText("");
                ImageIcon icon=new ImageIcon(preview.getScaledInstance(lblImagenProducto.getWidth(), lblImagenProducto.getHeight(), Image.SCALE_DEFAULT));
                lblImagenProducto.setIcon(icon);
            }
        }
        
    }//GEN-LAST:event_btnBuscarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMantenimientoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMantenimientoProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarArchivo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIrMenu;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cboNombreCategoria;
    private javax.swing.JComboBox cboNombreUniMed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFilas;
    private javax.swing.JLabel lblImagenProducto;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblLista;
    private javax.swing.JTextField txtCodProducto;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtRutaarchivo;
    // End of variables declaration//GEN-END:variables
}
