/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pckGui;

import javax.swing.JOptionPane;
import pckDao.classFecha;
import pckDao.classHoraSistema;

/**
 *
 * @author HOME
 */
public class frmMenu extends javax.swing.JFrame {
    classFecha oFechaSis=new classFecha();
    
    String idLogin="";
    void obtenercodLogin(String cod){
        idLogin=cod;
    }
    
    
     void mostrarFecha(){
        lblFecha.setText(oFechaSis.fechaActual());
    }
    
    void mostarAmPm(){
        lblAmPm.setText(oFechaSis.ObtenerAmPm());
    }
    
    void mostrarHora(){
        classHoraSistema hilo=new classHoraSistema(lblHora);
        try {
            hilo.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        mostrarHora();mostrarFecha();mostarAmPm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAmPm = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        mnItemCerrarSesion = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnItemSalir = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mnItemMantCategoria = new javax.swing.JMenuItem();
        mnItemMantUnidadMedida = new javax.swing.JMenuItem();
        mnItemMantProducto = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnItemMantMantCliente = new javax.swing.JMenuItem();
        mnItemMantUsuario = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnItemMantOpcionPago = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        mnItemBoleta = new javax.swing.JMenuItem();
        mnItemFactura = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        mnItemReporteProd = new javax.swing.JMenu();
        mnItemReporteProdporCategoria = new javax.swing.JMenuItem();
        mnItemReporteProdporUnidadMedida = new javax.swing.JMenuItem();
        mnItemReporteCategoria = new javax.swing.JMenuItem();
        mnItemReporteUnidadMedida = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnItemReporteVentas = new javax.swing.JMenu();
        mnItemVentasporFecha = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnItemVentasporBimestreAño = new javax.swing.JMenuItem();
        mnItemporTrimestreAño = new javax.swing.JMenuItem();
        mnItemSemestreAño = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnItemReporteVentasporCliente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú de Opciones");

        lblHora.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblFecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Bienvenido:"));

        jLabel1.setText("HORA:");

        jLabel2.setText("FECHA:");

        jMenu4.setText("Inicio");

        mnItemCerrarSesion.setText("Cerrar Sesion");
        mnItemCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemCerrarSesionActionPerformed(evt);
            }
        });
        jMenu4.add(mnItemCerrarSesion);
        jMenu4.add(jSeparator1);

        mnItemSalir.setText("Salir");
        mnItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemSalirActionPerformed(evt);
            }
        });
        jMenu4.add(mnItemSalir);

        jMenuBar2.add(jMenu4);

        jMenu6.setText("Mantenimiento");

        mnItemMantCategoria.setText("Categoria");
        mnItemMantCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemMantCategoriaActionPerformed(evt);
            }
        });
        jMenu6.add(mnItemMantCategoria);

        mnItemMantUnidadMedida.setText("Unidad Medida");
        mnItemMantUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemMantUnidadMedidaActionPerformed(evt);
            }
        });
        jMenu6.add(mnItemMantUnidadMedida);

        mnItemMantProducto.setText("Producto");
        mnItemMantProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemMantProductoActionPerformed(evt);
            }
        });
        jMenu6.add(mnItemMantProducto);
        jMenu6.add(jSeparator3);

        mnItemMantMantCliente.setText("Cliente");
        mnItemMantMantCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemMantMantClienteActionPerformed(evt);
            }
        });
        jMenu6.add(mnItemMantMantCliente);

        mnItemMantUsuario.setText("Usuario");
        mnItemMantUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemMantUsuarioActionPerformed(evt);
            }
        });
        jMenu6.add(mnItemMantUsuario);
        jMenu6.add(jSeparator4);

        mnItemMantOpcionPago.setText("Opción Pago");
        mnItemMantOpcionPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemMantOpcionPagoActionPerformed(evt);
            }
        });
        jMenu6.add(mnItemMantOpcionPago);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("Venta");

        mnItemBoleta.setText("Boleta");
        mnItemBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemBoletaActionPerformed(evt);
            }
        });
        jMenu7.add(mnItemBoleta);

        mnItemFactura.setText("Factura");
        mnItemFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemFacturaActionPerformed(evt);
            }
        });
        jMenu7.add(mnItemFactura);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("Consulta");

        mnItemReporteProd.setText("Productos");

        mnItemReporteProdporCategoria.setText("Por Categoria");
        mnItemReporteProdporCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemReporteProdporCategoriaActionPerformed(evt);
            }
        });
        mnItemReporteProd.add(mnItemReporteProdporCategoria);

        mnItemReporteProdporUnidadMedida.setText("Por Unidad Medida");
        mnItemReporteProdporUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemReporteProdporUnidadMedidaActionPerformed(evt);
            }
        });
        mnItemReporteProd.add(mnItemReporteProdporUnidadMedida);

        jMenu8.add(mnItemReporteProd);

        mnItemReporteCategoria.setText("Categoria");
        mnItemReporteCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemReporteCategoriaActionPerformed(evt);
            }
        });
        jMenu8.add(mnItemReporteCategoria);

        mnItemReporteUnidadMedida.setText("Unidad Medida");
        mnItemReporteUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemReporteUnidadMedidaActionPerformed(evt);
            }
        });
        jMenu8.add(mnItemReporteUnidadMedida);
        jMenu8.add(jSeparator2);

        mnItemReporteVentas.setText("Ventas");

        mnItemVentasporFecha.setText("Por Fecha");
        mnItemVentasporFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemVentasporFechaActionPerformed(evt);
            }
        });
        mnItemReporteVentas.add(mnItemVentasporFecha);
        mnItemReporteVentas.add(jSeparator6);

        mnItemVentasporBimestreAño.setText("Por Bimestre del Año");
        mnItemVentasporBimestreAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemVentasporBimestreAñoActionPerformed(evt);
            }
        });
        mnItemReporteVentas.add(mnItemVentasporBimestreAño);

        mnItemporTrimestreAño.setText("Por Trimestre del Año");
        mnItemporTrimestreAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemporTrimestreAñoActionPerformed(evt);
            }
        });
        mnItemReporteVentas.add(mnItemporTrimestreAño);

        mnItemSemestreAño.setText("Por Semestre del Año");
        mnItemSemestreAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemSemestreAñoActionPerformed(evt);
            }
        });
        mnItemReporteVentas.add(mnItemSemestreAño);
        mnItemReporteVentas.add(jSeparator5);

        mnItemReporteVentasporCliente.setText("Por Cliente");
        mnItemReporteVentasporCliente.setRequestFocusEnabled(false);
        mnItemReporteVentasporCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemReporteVentasporClienteActionPerformed(evt);
            }
        });
        mnItemReporteVentas.add(mnItemReporteVentasporCliente);

        jMenu8.add(mnItemReporteVentas);

        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 675, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAmPm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 613, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(lblAmPm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemCerrarSesionActionPerformed
        // TODO add your handling code here:
        frmInicioSesion vent=new frmInicioSesion();
        vent.setLocationRelativeTo(null);vent.setResizable(false);vent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mnItemCerrarSesionActionPerformed

    private void mnItemBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemBoletaActionPerformed
        // TODO add your handling code here:
        
        frmMantenimientoVenta vent=new frmMantenimientoVenta();
       
        vent.setResizable(false);
        vent.setVisible(true);
        vent.obtenerIdLogin(idLogin);
        vent.lblUsuario.setText(lblUsuario.getText());
        vent.lblDocumento.setText("DNI:");
        vent.DiseñoTitulo("Boleta",8);
        vent.lblNombRazonSocial.setText("Nombres y Apellidos:");
    }//GEN-LAST:event_mnItemBoletaActionPerformed

    private void mnItemFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemFacturaActionPerformed
        // TODO add your handling code here:
    
        
        frmMantenimientoVenta vent=new frmMantenimientoVenta();
       
        vent.setResizable(false);
        vent.setVisible(true);
        vent.lblUsuario.setText(lblUsuario.getText());
         vent.obtenerIdLogin(idLogin);
        vent.lblDocumento.setText("RUC:");
        vent.DiseñoTitulo("Factura",11);
        vent.lblNombRazonSocial.setText("Razon Social:");
    }//GEN-LAST:event_mnItemFacturaActionPerformed

    private void mnItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemSalirActionPerformed
        // TODO add your handling code here:
        int x=JOptionPane.showConfirmDialog(this,"Seguro de Cerrar la Aplicacion");
        if(x==0){
            System.exit(0);
        }
    }//GEN-LAST:event_mnItemSalirActionPerformed

    private void mnItemMantOpcionPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemMantOpcionPagoActionPerformed
        // TODO add your handling code here:
        frmListarOpcionPago vent=new frmListarOpcionPago();
        vent.setLocationRelativeTo(null);vent.setResizable(false);
        vent.setVisible(true);vent.obtenerIdLogin(idLogin);
        vent.lblUsuario.setText(lblUsuario.getText());
    }//GEN-LAST:event_mnItemMantOpcionPagoActionPerformed

    private void mnItemMantUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemMantUsuarioActionPerformed
        // TODO add your handling code here:
         frmMantenimientoUsuario vent=new frmMantenimientoUsuario();
         vent.setLocationRelativeTo(null);
        vent.setResizable(false);vent.obtenerIdLogin(idLogin);
        vent.setVisible(true);vent.lblUsuario.setText(lblUsuario.getText());
    }//GEN-LAST:event_mnItemMantUsuarioActionPerformed

    private void mnItemMantMantClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemMantMantClienteActionPerformed
        // TODO add your handling code here:
         frmMantenimientoCliente vent=new frmMantenimientoCliente();
         vent.setLocationRelativeTo(null);
        vent.setResizable(false);vent.obtenerIdLogin(idLogin);
        vent.setVisible(true);vent.lblUsuario.setText(lblUsuario.getText());
    }//GEN-LAST:event_mnItemMantMantClienteActionPerformed

    private void mnItemMantProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemMantProductoActionPerformed
        // TODO add your handling code here:
         frmMantenimientoProductos vent=new frmMantenimientoProductos();
         vent.setLocationRelativeTo(null);
        vent.setResizable(false);vent.obtenerIdLogin(idLogin);
        vent.setVisible(true);vent.lblUsuario.setText(lblUsuario.getText());
    }//GEN-LAST:event_mnItemMantProductoActionPerformed

    private void mnItemMantUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemMantUnidadMedidaActionPerformed
        // TODO add your handling code here:
         frmListarUnidadMedida vent=new frmListarUnidadMedida();
         vent.setLocationRelativeTo(null);
        vent.setResizable(false);vent.obtenerIdLogin(idLogin);
        vent.setVisible(true);vent.lblUsuario.setText(lblUsuario.getText());
    }//GEN-LAST:event_mnItemMantUnidadMedidaActionPerformed

    private void mnItemMantCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemMantCategoriaActionPerformed
        // TODO add your handling code here:
         frmListarCategoria vent=new frmListarCategoria();
         vent.setLocationRelativeTo(null);
        vent.setResizable(false);
      vent.obtenerIdLogin(idLogin);
        vent.setVisible(true);vent.lblUsuario.setText(lblUsuario.getText());
    }//GEN-LAST:event_mnItemMantCategoriaActionPerformed

    private void mnItemReporteProdporCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemReporteProdporCategoriaActionPerformed
        // TODO add your handling code here:
         frmReporteProductosporCategoria vent=new frmReporteProductosporCategoria();
         vent.setLocationRelativeTo(null);
        vent.setResizable(false);
        vent.setVisible(true);vent.lblUsuario.setText(lblUsuario.getText());
    }//GEN-LAST:event_mnItemReporteProdporCategoriaActionPerformed

    private void mnItemReporteProdporUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemReporteProdporUnidadMedidaActionPerformed
        // TODO add your handling code here:
         frmReporteProductosporUnidadMedida vent=new frmReporteProductosporUnidadMedida();
         vent.setLocationRelativeTo(null);
        vent.setResizable(false);
        vent.setVisible(true);vent.lblUsuario.setText(lblUsuario.getText());
    }//GEN-LAST:event_mnItemReporteProdporUnidadMedidaActionPerformed

    private void mnItemReporteCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemReporteCategoriaActionPerformed
        // TODO add your handling code here:
        frmReporteProductosporCategoria vent=new frmReporteProductosporCategoria();
        vent.setVisible(true);
    }//GEN-LAST:event_mnItemReporteCategoriaActionPerformed

    private void mnItemReporteUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemReporteUnidadMedidaActionPerformed
        // TODO add your handling code here:
        frmReporteProductosporUnidadMedida vent=new frmReporteProductosporUnidadMedida();
        vent.setVisible(true);vent.lblUsuario.setText(lblUsuario.getText());
    }//GEN-LAST:event_mnItemReporteUnidadMedidaActionPerformed

    private void mnItemReporteVentasporClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemReporteVentasporClienteActionPerformed
        // TODO add your handling code here:
        frmReporteVentasporCliente vent=new frmReporteVentasporCliente();
        vent.setVisible(true);vent.lblUsuario.setText(lblUsuario.getText());
    }//GEN-LAST:event_mnItemReporteVentasporClienteActionPerformed

    private void mnItemVentasporFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemVentasporFechaActionPerformed
        // TODO add your handling code here:
        frmReporteVentasporFecha vent=new frmReporteVentasporFecha();
        vent.setVisible(true);vent.lblUsuario.setText(lblUsuario.getText());
    }//GEN-LAST:event_mnItemVentasporFechaActionPerformed

    private void mnItemVentasporBimestreAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemVentasporBimestreAñoActionPerformed
        // TODO add your handling code here:
        frmReporteVentasporBimestre vent=new frmReporteVentasporBimestre();
        vent.setVisible(true);vent.lblUsuario.setText(lblUsuario.getText());
    }//GEN-LAST:event_mnItemVentasporBimestreAñoActionPerformed

    private void mnItemporTrimestreAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemporTrimestreAñoActionPerformed
        // TODO add your handling code here:
        frmReporteVentasporTrimestre vent=new frmReporteVentasporTrimestre();
        vent.setVisible(true);vent.lblUsuario.setText(lblUsuario.getText());
    }//GEN-LAST:event_mnItemporTrimestreAñoActionPerformed

    private void mnItemSemestreAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemSemestreAñoActionPerformed
        // TODO add your handling code here:
        frmReporteVentasporSemestre vent=new frmReporteVentasporSemestre();
        vent.setVisible(true);vent.lblUsuario.setText(lblUsuario.getText());
    }//GEN-LAST:event_mnItemSemestreAñoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu4;
    public static javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    public static javax.swing.JLabel lblAmPm;
    public static javax.swing.JLabel lblFecha;
    public static javax.swing.JLabel lblHora;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem mnItemBoleta;
    private javax.swing.JMenuItem mnItemCerrarSesion;
    private javax.swing.JMenuItem mnItemFactura;
    private javax.swing.JMenuItem mnItemMantCategoria;
    private javax.swing.JMenuItem mnItemMantMantCliente;
    private javax.swing.JMenuItem mnItemMantOpcionPago;
    private javax.swing.JMenuItem mnItemMantProducto;
    private javax.swing.JMenuItem mnItemMantUnidadMedida;
    private javax.swing.JMenuItem mnItemMantUsuario;
    private javax.swing.JMenuItem mnItemReporteCategoria;
    private javax.swing.JMenu mnItemReporteProd;
    private javax.swing.JMenuItem mnItemReporteProdporCategoria;
    private javax.swing.JMenuItem mnItemReporteProdporUnidadMedida;
    private javax.swing.JMenuItem mnItemReporteUnidadMedida;
    private javax.swing.JMenu mnItemReporteVentas;
    private javax.swing.JMenuItem mnItemReporteVentasporCliente;
    private javax.swing.JMenuItem mnItemSalir;
    private javax.swing.JMenuItem mnItemSemestreAño;
    private javax.swing.JMenuItem mnItemVentasporBimestreAño;
    private javax.swing.JMenuItem mnItemVentasporFecha;
    private javax.swing.JMenuItem mnItemporTrimestreAño;
    // End of variables declaration//GEN-END:variables
}
