/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pckGui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pckDao.classProductoDao;
import pckDao.classReporteDao;
import pckDao.classUnidadMedida;
import pckEntidad.ProductoConsulta;
import pckEntidad.UnidadMedida;

/**
 *
 * @author HOME
 */
public class frmReporteProductosporUnidadMedida extends javax.swing.JFrame {
    classProductoDao oProductoDao=new classProductoDao();
    
    
    
    void cargarUnidadMedida(){
        classUnidadMedida oUnidadMedidaDao=new classUnidadMedida();
        ArrayList<UnidadMedida> lista=oUnidadMedidaDao.listarUnidadMedida();
        for (UnidadMedida ounidadMedida : lista) {
            cboUnidadMedida.addItem(ounidadMedida.getNombreMedida());
        }
    }
    void listarProductosporUnidadMedida(){
        DefaultTableModel mod=new DefaultTableModel();
        String columnas[]={
          "Codigo","Producto","Unidad Medida","Precio Unitario","Categoria"  
        };mod.setColumnIdentifiers(columnas);
        ArrayList<ProductoConsulta> lista=oProductoDao.listarProductosDetallado();
        for (ProductoConsulta oproductoConsulta : lista) {
            Object data[]={
                oproductoConsulta.getIdProducto(),oproductoConsulta.getNombreProd(),oproductoConsulta.getNombreUnidadMedida(),oproductoConsulta.getPrecioUnitario(),oproductoConsulta.getNombreCategoria()
            };mod.addRow(data);
        }tblProdporCategoria.setModel(mod);lblFilas.setText("Filas Encontradas: "+tblProdporCategoria.getRowCount());
    }
    void listarProductosporUnidadMedida(int codUnidadMedida){
        DefaultTableModel mod=new DefaultTableModel();
        String columnas[]={
          "Codigo","Producto","Unidad Medida","Precio Unitario","Categoria"  
        };mod.setColumnIdentifiers(columnas);
        ArrayList<ProductoConsulta> lista=oProductoDao.listarProductosporUnidadMedida(codUnidadMedida);
        for (ProductoConsulta oproductoConsulta : lista) {
            Object data[]={
                oproductoConsulta.getIdProducto(),oproductoConsulta.getNombreProd(),oproductoConsulta.getNombreUnidadMedida(),oproductoConsulta.getPrecioUnitario(),oproductoConsulta.getNombreCategoria()
            };mod.addRow(data);
        }tblProdporCategoria.setModel(mod);lblFilas.setText("Filas Encontradas: "+tblProdporCategoria.getRowCount());
        
    }
    void consultar(){
        int x=cboUnidadMedida.getSelectedIndex();
        if(x==0){
            listarProductosporUnidadMedida();
        }else if(x>0){
            listarProductosporUnidadMedida(x);
        }
    }
    
    
    /**
     * Creates new form frmReporteProductosporUnidadMedida
     */
    
    
    public frmReporteProductosporUnidadMedida() {
        initComponents();
        consultar();
        cargarUnidadMedida();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboUnidadMedida = new javax.swing.JComboBox();
        lblUnidadMedida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdporCategoria = new javax.swing.JTable();
        pnlControles = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGenerarReporte = new javax.swing.JButton();
        btnIraMenu = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblFilas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboUnidadMedida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Todos--" }));
        cboUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboUnidadMedidaActionPerformed(evt);
            }
        });

        lblUnidadMedida.setText("Unidad Medida:");

        tblProdporCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProdporCategoria);

        pnlControles.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Controles:"));

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGenerarReporte.setText("GENERAR REPORTE");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        btnIraMenu.setText("Ir a Menú");
        btnIraMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIraMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlesLayout = new javax.swing.GroupLayout(pnlControles);
        pnlControles.setLayout(pnlControlesLayout);
        pnlControlesLayout.setHorizontalGroup(
            pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGenerarReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIraMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlControlesLayout.setVerticalGroup(
            pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo)
                .addGap(18, 18, 18)
                .addComponent(btnGenerarReporte)
                .addGap(18, 18, 18)
                .addComponent(btnIraMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Usuario:"));

        lblFilas.setText("Filas Encontradas: xx");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUnidadMedida)
                            .addComponent(cboUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFilas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblUnidadMedida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cboUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblFilas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboUnidadMedidaActionPerformed
        // TODO add your handling code here:
        consultar();
    }//GEN-LAST:event_cboUnidadMedidaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        cboUnidadMedida.setSelectedIndex(0);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnIraMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIraMenuActionPerformed
        // TODO add your handling code here:
//        frmMenu vent=new frmMenu();
//        vent.setLocationRelativeTo(null);
//        vent.setResizable(false);vent.lblUsuario.setText(lblUsuario.getText());
//        vent.setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnIraMenuActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        // TODO add your handling code here:
        classReporteDao report=new classReporteDao();
        if(cboUnidadMedida.getSelectedIndex()==0){
            JOptionPane.showConfirmDialog(this,"Seleccione una Unidad Medida");
        }else {
            report.startReporteProductosUnidadMedida(cboUnidadMedida.getSelectedIndex());
        }
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteProductosporUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteProductosporUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteProductosporUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteProductosporUnidadMedida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReporteProductosporUnidadMedida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnIraMenu;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cboUnidadMedida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFilas;
    private javax.swing.JLabel lblUnidadMedida;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlControles;
    private javax.swing.JTable tblProdporCategoria;
    // End of variables declaration//GEN-END:variables
}
