/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pckGui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pckDao.classCategoriaDao;
import pckDao.classProductoDao;
import pckDao.classReporteDao;
import pckEntidad.Categoria;
import pckEntidad.ProductoConsulta;

/**
 *
 * @author HOME
 */
public class frmReporteProductosporCategoria extends javax.swing.JFrame {
    
    classProductoDao oProductoDao=new classProductoDao();
    
   
    void listarProductos(){
        DefaultTableModel mod=new DefaultTableModel();
        String []columnas={
          "Codigo","Producto","Unidad Medida","Precio Unitario","Categoria"  
        };mod.setColumnIdentifiers(columnas);
        tblProdporCategoria.setModel(new DefaultTableModel());
        
        ArrayList<ProductoConsulta> lista=oProductoDao.listarProductosDetallado();
        for (ProductoConsulta oproductoConsulta : lista) {
            Object data[]={
              oproductoConsulta.getIdProducto(),oproductoConsulta.getNombreProd(),oproductoConsulta.getNombreUnidadMedida(),oproductoConsulta.getPrecioUnitario(),oproductoConsulta.getNombreCategoria()
            };mod.addRow(data);
        }tblProdporCategoria.setModel(mod);lblfilas.setText("Filas Encontradas: "+tblProdporCategoria.getRowCount());
    }
    
    void listarProductoporCategoria(int idCategoria){
       DefaultTableModel mod=new DefaultTableModel();
        String []columnas={
          "Codigo","Producto","Unidad Medida","Precio Unitario","Categoria"  
        };mod.setColumnIdentifiers(columnas);
        
        ArrayList<ProductoConsulta> lista=oProductoDao.listarProductosporCategoria(idCategoria);
        for (ProductoConsulta oproductoConsulta : lista) {
            Object data[]={
              oproductoConsulta.getIdProducto(),oproductoConsulta.getNombreProd(),oproductoConsulta.getNombreUnidadMedida(),oproductoConsulta.getPrecioUnitario(),oproductoConsulta.getNombreCategoria()
            };mod.addRow(data);
        }tblProdporCategoria.setModel(mod);lblfilas.setText("Filas Encontradas: "+tblProdporCategoria.getRowCount());
    }
    
    void cargarNombreCategoria(){
        classCategoriaDao oCategoriaDao=new classCategoriaDao();
        ArrayList<Categoria> lista=oCategoriaDao.listarCategoria();
        for (Categoria ocategoria : lista) {
            cboCategoria.addItem(ocategoria.getNombreCategoria());
        }
    }
    void consulta(){
         int x=cboCategoria.getSelectedIndex();
        
        if(x==0){
            listarProductos();
        }else if(x>0){
            listarProductoporCategoria(x);
        }
    }
    /**
     * Creates new form frmReporteProductosporCategoria
     */
    public frmReporteProductosporCategoria() {
        initComponents();
        cargarNombreCategoria();
        consulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboCategoria = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdporCategoria = new javax.swing.JTable();
        lblfilas = new javax.swing.JLabel();
        pnlControles = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnGenerarReporte = new javax.swing.JButton();
        btnIraMenu = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Todos--" }));
        cboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCategoriaActionPerformed(evt);
            }
        });

        jLabel1.setText("Categoria:");

        tblProdporCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblProdporCategoria);

        lblfilas.setText("Filas Encontradas: xx");

        pnlControles.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Controles:"));

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGenerarReporte.setText("GENERAR REPORTE");
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });

        btnIraMenu.setText("Ir a Menú");
        btnIraMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIraMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlControlesLayout = new javax.swing.GroupLayout(pnlControles);
        pnlControles.setLayout(pnlControlesLayout);
        pnlControlesLayout.setHorizontalGroup(
            pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGenerarReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIraMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlControlesLayout.setVerticalGroup(
            pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo)
                .addGap(18, 18, 18)
                .addComponent(btnGenerarReporte)
                .addGap(18, 18, 18)
                .addComponent(btnIraMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Usuario:"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblfilas)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlControles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlControles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblfilas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCategoriaActionPerformed
        // TODO add your handling code here:
        consulta();
    }//GEN-LAST:event_cboCategoriaActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        cboCategoria.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnIraMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIraMenuActionPerformed
        // TODO add your handling code here:
//        frmMenu vent=new frmMenu();
//        vent.setLocationRelativeTo(null);
//        vent.setResizable(false);
//        vent.lblUsuario.setText(lblUsuario.getText());
//        vent.setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnIraMenuActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        // TODO add your handling code here:
        classReporteDao report = new classReporteDao();
      
        if(cboCategoria.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(this,"Seleccione una Categoria");
        }else {
        report.startReporteProductosporCategoria(cboCategoria.getSelectedIndex());
        }
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReporteProductosporCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReporteProductosporCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReporteProductosporCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReporteProductosporCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReporteProductosporCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReporte;
    private javax.swing.JButton btnIraMenu;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cboCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblfilas;
    private javax.swing.JPanel pnlControles;
    private javax.swing.JTable tblProdporCategoria;
    // End of variables declaration//GEN-END:variables
}
