/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pckGui;

import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/**
 *
 * @author HOME
 */
public class frmVisualizarVenta extends javax.swing.JFrame {

    void impresion(String texto){
        txtvistaPreviaBoleta.append(texto+"\n");
    }
    
    /**
     * Creates new form frmVisualizarVenta
     */
    public frmVisualizarVenta() {
        initComponents();
        txtvistaPreviaBoleta.removeAll();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtvistaPreviaBoleta = new javax.swing.JTextArea();
        btnImprimir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtvistaPreviaBoleta.setColumns(20);
        txtvistaPreviaBoleta.setRows(5);
        jScrollPane1.setViewportView(txtvistaPreviaBoleta);

        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
         PaginaEjemplo pagination =new PaginaEjemplo();
        pagination.imprimir();
    }//GEN-LAST:event_btnImprimirActionPerformed

    
    
       public class PaginaEjemplo implements Printable{
        
        StringTokenizer lineatexto = new StringTokenizer(txtvistaPreviaBoleta.getText(),"\n",true);
        
        int total_lineas=lineatexto.countTokens();
        
        int[] paginas;
        String[] textoLineas;
        
        public int print(Graphics g, PageFormat pf,int pageIndex) throws PrinterException{
            
            Font font=new Font("Courier new",Font.ITALIC,16);
            FontMetrics metrices=g.getFontMetrics(font);
            
            int altolinea=metrices.getHeight();
            
            if(paginas==null){
                
                iniTextoLineas();
                
                int lineasxPaginas=(int)(pf.getImageableHeight()/altolinea);
                
                int numeroPaginas=(textoLineas.length-1)/lineasxPaginas;
                paginas = new int[numeroPaginas];
                
                for(int b=0;b<numeroPaginas;b++){
                paginas[b]=(b+1)*lineasxPaginas;
                }
                
            }
            if(pageIndex>paginas.length){
                return NO_SUCH_PAGE;
            }
            
            Graphics2D g2d=(Graphics2D)g;
            g2d.translate(pf.getImageableX(),pf.getImageableY());
            
            int y=0;
            int start=(pageIndex==0) ? 0 : paginas[pageIndex-1];
            int end=(pageIndex==paginas.length) ? textoLineas.length : paginas[pageIndex];
            
            for(int line=start ; line<end ; line++){
            y+=altolinea;
            g.drawString(textoLineas[line], 0, y);
        }
            return PAGE_EXISTS;
            
            
        }
        public void iniTextoLineas(){
            if(textoLineas==null){
                int numLineas=total_lineas;
                
                while(lineatexto.hasMoreTokens()){
                    for(int i=0;i<numLineas;i++){
                        textoLineas[i]=lineatexto.nextToken();
                    }
                }
                
                
            }
        }
        
        public void imprimir(){ PrinterJob job=PrinterJob.getPrinterJob();
        job.setPrintable(this);
        
        boolean ok=job.printDialog();
        
        if(ok){
            try{
                job.print();
            }catch(PrinterException ex){
                
                JOptionPane.showMessageDialog(null, ex);
                
            }
        }
            
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVisualizarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVisualizarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVisualizarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVisualizarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVisualizarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtvistaPreviaBoleta;
    // End of variables declaration//GEN-END:variables
}
